method_group:
  method_name: uncertainty_aware_mean_teacher
  train_transform: random
  consistency: 0.1
  consistency_rampup: 200.0
  uncertainty_passes: 8
  uncertainty_threshold_base: 0.75
  uncertainty_threshold_scale: 0.25
ema_group:
  ema: true
  ema_decay: 0.99
